### PR TITLE
fix: promise never returned on table.insert

### LINKED ISSUE #948: table.insert does not return a Promise
`table.insert` does not return a promise or has a dangling one

1) Is this a client library issue or a product issue?
Client library issue

2) Did someone already solve this?
Node

3) Do you have a support contract?
No

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS: MacOs
  - Node.js version: v14.16.1
  - npm version: 6.14.12
  - `@google-cloud/bigquery` version: 5.5.0

#### Steps to reproduce

1) Call `table.insert` without a callback and wrap it in a try/catch, as in:

```js
try {
  await this.table.insert({...});
} catch (error) {
 ...
}
```

2) If the data has a wrong type, then the call will have an Unhandled rejection.

Below are the errors:
```
Unhandled rejection
Unhandled rejection
PartialFailureError at Table._insert (/workspace/node_modules/@google-cloud/bigquery/build/src/table.js:1611:19)
                               at processTicksAndRejections (internal/process/task_queues.js:97:5)
                               at async Table._insertWithRetry (/workspace/node_modules/@google-cloud/bigquery/build/src/table.js:1548:24)
                               at async Table._insertAndCreateTable (/workspace/node_modules/@google-cloud/bigquery/build/src/table.js:1510:20)
```

### PR DESCRIPTION
**Pull request by larssn**
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-bigquery/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #948 

So the `table.insert` function never returned its promise. This PR fixes that.
It also gets rid of an unnecessary cast.

Two new tests were written:
- `it should return a promise if no callback is provided`
- `it should resolve to an array on success`

Code coverage goes down to 99.92, due to line 1916 being uncovered (even though thats what the new tests were for).

### CODE REVIEW

File: src/table.ts [hunk 1]
```diff
@@ -1904,14 +1904,17 @@ class Table extends common.ServiceObject {
...
-      err => callback(err, null)
-    );
+    const promise = this._insertAndCreateTable(rows, options);
+    if (callback) {
+      promise.then(
+        resp => callback(null, resp),
+        err => callback(err, null)
+      );
+    } else {
+      return promise.then(r => [r]);
```
Comment (feywind) [inline src/table.ts:1916]: It's sort of odd to me that the Promise returns an array, but the callback isn't called with one. This seems to maintain the method definition though.

**Review by feywind — APPROVED** [review]
I disagree with codecov, I think those lines are covered.

File: src/table.ts [hunk 2]
```diff
@@ -1904,14 +1904,17 @@ class Table extends common.ServiceObject {
...
-        ? optionsOrCallback
-        : (cb as InsertRowsCallback);
+      typeof optionsOrCallback === 'function' ? optionsOrCallback : cb;
 
-    this._insertAndCreateTable(rows, options).then(
-      resp => callback(null, resp),
-      err => callback(err, null)
-    );
+    const promise = this._insertAndCreateTable(rows, options);
+    if (callback) {
```
Comment (sk-) [inline src/table.ts:1910]: I don't think this is needed, as there's already a promisified version being returned. See https://github.com/googleapis/nodejs-bigquery/blob/a138347855f74d4e5c889dc42b00992c4a3808a6/src/table.ts#L2388.

I think the unhandled rejection may come from further down.

File: src/table.ts (hunk 1 above)
Comment (larssn) [reply src/table.ts:1916]: Or it could be typescript having trouble determining the return type.
I'm not sure if there's a test for the callback version's return type.

File: src/table.ts (hunk 2 above)
Comment (larssn) [reply src/table.ts:1910]: You're right, this PR fixes nothing then. Easy to miss. Not the biggest fan of code like that tbh.

cc @feywind
