### PR TITLE
testing: remove nextQuery assertion

### LINKED ISSUE #375: The system tests, they are broken.

### PR DESCRIPTION
**Pull request by callmehiphop**
Fixes #375 

Since we refactored our strategy for dealing with lingering resources, sometimes `nextQuery` will be populated with a page of resources from a different test run. 

- [x] Tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

### CODE REVIEW

File: system-test/bigquery.ts [hunk 1]
```diff
@@ -176,7 +176,6 @@ describe('BigQuery', () => {
       filter: `labels.${GCLOUD_TESTS_PREFIX}`,
     });
     assert(datasets[0] instanceof Dataset);
-    assert.strictEqual(nextQuery, null);
```
Comment (bcoe) [inline system-test/bigquery.ts]: seems reasonable to me; in a perfect world, I might try to have a `beforeEach` that ensures that there's nothing populated in `nextQuery` before running the test. Is there a tracking issue for this bug? (state between tests can really start to be a pain).

Comment (callmehiphop) [reply system-test/bigquery.ts]: I don't think there is, @JustinBeckwith might know though?
