### PR TITLE
fix(docs): fix formatting of the docs

### LINKED ISSUE #504: Broken code examples in BigQuery documentation
The documentation under https://googleapis.dev/nodejs/bigquery/latest/BigQuery.html has HTML tags in the code examples (e.g. `<caption>` tags):

```
<caption>Install the client library with <a
href="https://www.npmjs.com/">npm</a>:</caption> npm install --save
```

### PR DESCRIPTION
**Pull request by JustinBeckwith**
Fixes #504

Looking a little better ....

image

### CODE REVIEW

File: src/table.ts [hunk 1]
```diff
@@ -1395,7 +1395,9 @@ class Table extends common.ServiceObject {
           } as {},
           request: {
             uri: format('{base}/{projectId}/jobs', {
-              base: `https://${this.bigQuery.apiEndpoint}/upload/bigquery/v2/projects`,
+              base: `https://${
```
Comment (callmehiphop) [inline src/table.ts]: Looks like this is throwing a lint error? Might just need a `fix`
